name: changelog-check

on:
  pull_request:
    branches:
      - "develop"

permissions:
  contents: read

jobs:
  Check-Changelog:
    name: Check Changelog Action
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit

      - uses: tarides/changelog-check-action@47122075af50b17dbf68f7d059c88c99f082ac43 # v2
        with:
          changelog: CHANGELOG.md
