name: changelog-check

on:
  pull_request:

permissions:
  contents: read

jobs:
  Check-Changelog:
    name: Check Changelog Action
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ccd8616d44fd3846e67624a50d5aad6d37bf2d25 # v2.22.1
        with:
          egress-policy: audit

      - uses: tarides/changelog-check-action@0189fc7eedec3ef3e9648c713908f6f2a6e99057 # v3
        with:
          changelog: CHANGELOG.md
